name: Build and Deploy

on:
  push:
    branches:
      - main  
      
permissions:
  contents: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        cordova-version: 8
        install-java: false
        install-pods: false

    - name: Checkout
      uses: actions/checkout@v1

    - name: Install NPM Modules
      run: |
        npm i -D -E @angular/cli
        npm install --force

    - name: Inject API Key into Environment File
      run: |
        echo "export const environment = {" > src/environments/environment.prod.ts
        echo "  production: true," >> src/environments/environment.prod.ts
        echo "  workoutPlanBaseUrl: 'https://musclemadness.co.in/datasource/'," >> src/environments/environment.prod.ts
        echo "  defaultWorkoutPlanUrl: '../../assets/data/default-workout-plan.json'," >> src/environments/environment.prod.ts
        echo "  googleDriveApiKey: '${{ secrets.GOOGLE_DRIVE_API_KEY }}'," >> src/environments/environment.prod.ts
        echo "  googleSignInClientId: '${{ secrets.GOOGLE_CLIENT_ID }}'" >> src/environments/environment.prod.ts
        echo "};" >> src/environments/environment.prod.ts

    - name: Build
      run: |
        ionic build --prod -- --base-href 'https://training.musclemadness.co.in'
        ls www

    - name: Add CNAME file
      run: echo 'training.musclemadness.co.in' > www/CNAME

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: www
